package com.nu1r.jndi.enumtypes;

public enum PayloadType {
    dnslog,
    tomcatupgrade,
    nu1r,
    reverseshell,
    tomcatecho,
    springecho,
    AllEcho,
    tomcatfilterjmx,
    tomcatfilterth,
    tomcatlistenerjmx,
    tomcatlistenerth,
    tomcatservletjmx,
    tomcatservletth,
    jbossfilter,
    jbossservlet,
    webspherememshell,
    springinterceptor,
    springcontroller,
    issuccess,
    jettyfilter,
    jettyservlet,
    wsfilter,
    tomcatexecutor,
    meterpreter,
    resinfilterth,
    resinservletth,
    jbossecho,
}
