package com.qi4l.jndi.enumtypes;

public enum PayloadType {
    dnslog,
    tomcatupgrade,
    command,
    reverseshell,
    tomcatecho,
    springecho,
    weblogicecho,
    windowsecho,
    linuxecho2,
    linuxecho1,
    allecho,
    websphereecho,
    resinecho,
    struts2echo,
    tomcatfilterjmx,
    tomcatfilterth,
    tomcatlistenerjmx,
    tomcatlistenerth,
    tomcatservletjmx,
    tomcatservletth,
    jbossfilter,
    jbossservlet,
    webspherememshell,
    springinterceptor,
    springcontroller,
    issuccess,
    jettyfilter,
    jettyservlet,
    struts2actionms,
    wsfilter,
    tomcatexecutor,
    meterpreter,
    resinfilterth,
    resinservletth,
    jbossecho,
    jettyecho, Struts2ActionMS,
}
