package com.feihong.ldap.enumtypes;

public enum GadgetType {
    urldns,
    commonsbeanutils1,
    commonsbeanutils2,
    commonscollections1,
    commonscollections1_1,
    commonscollections2,
    commonscollections3,
    commonscollections4,
    commonscollections5,
    commonscollections6,
    commonscollections7,
    commonscollectionsk1,
    commonscollectionsk2,
    commonscollectionsk3,
    commonscollectionsk4,
    jdk7u21,
    jre8u20,
    c3p0,
    AspectJWeaver,
    BeanShell1,
    C3P092,
    Click1,
    Clojure,
    CommonsBeanutils2NOCC,
    CommonsBeanutils3,
    CommonsBeanutils1183NOCC,
    CommonsBeanutils3183,
    cve_2020_2555,
    cve_2020_2883;
}
